import type { Student, CallLog, AttendanceRecord } from './types';

export const mockStudents: Student[] = [
  {
    id: '1',
    name: 'علی رضایی',
    username: 'ali.rezaei',
    role: 'فراگیر',
    status: 'active',
    withdrawalWarning: false,
    course: 'Python پیشرفته',
    term: 'ترم سوم',
    termNumber: 3,
    startDate: '2025-09-01',
    currentWeek: 8,
    currentTopic: 'هفته ۸ - برنامه‌نویسی شی‌گرا',
    subscriptionPlan: 'premium',
    phase: 'فاز ۳ - پروژه پایتون',
    progress: 72,
    lastContact: '2026-07-20',
    classesCompleted: 16,
    totalClasses: 24,
    reportCardDone: true,
  },
  {
    id: '2',
    name: 'فاطمه محمدی',
    username: 'fatemeh.mohammadi',
    role: 'فراگیر',
    status: 'active',
    withdrawalWarning: true,
    course: 'Scratch مقدماتی',
    term: 'ترم اول',
    termNumber: 1,
    startDate: '2026-01-15',
    currentWeek: 4,
    currentTopic: 'هفته ۴ - اسکرچ و شخصیت‌ها',
    subscriptionPlan: 'economy',
    phase: 'فاز ۱ - آشنایی با اسکرچ',
    progress: 38,
    lastContact: '2026-06-10',
    classesCompleted: 7,
    totalClasses: 18,
    reportCardDone: false,
  },
  {
    id: '3',
    name: 'امیر حسینی',
    username: 'amir.hosseini',
    role: 'فراگیر',
    status: 'active',
    withdrawalWarning: false,
    course: 'App Inventor',
    term: 'ترم دوم',
    termNumber: 2,
    startDate: '2025-11-01',
    currentWeek: 10,
    currentTopic: 'هفته ۱۰ - ساخت اپلیکیشن موبایل',
    subscriptionPlan: 'vip',
    phase: 'فاز ۴ - پروژه اپ اینونتور',
    progress: 88,
    lastContact: '2026-08-01',
    classesCompleted: 20,
    totalClasses: 24,
    reportCardDone: true,
  },
  {
    id: '4',
    name: 'زهرا کریمی',
    username: 'zahra.karimi',
    role: 'فراگیر',
    status: 'suspended',
    withdrawalWarning: false,
    course: 'هوش مصنوعی مقدماتی',
    term: 'ترم دوم',
    termNumber: 2,
    startDate: '2025-10-15',
    currentWeek: 6,
    currentTopic: 'هفته ۶ - یادگیری ماشین پایه',
    subscriptionPlan: 'premium',
    phase: 'فاز ۲ - مدل‌های ساده',
    progress: 52,
    lastContact: '2026-05-20',
    classesCompleted: 12,
    totalClasses: 20,
    reportCardDone: false,
    suspensionReason: 'عدم پرداخت شهریه',
  },
  {
    id: '5',
    name: 'محمد احمدی',
    username: 'mohammad.ahmadi',
    role: 'فراگیر',
    status: 'active',
    withdrawalWarning: false,
    course: 'IoT',
    term: 'ترم اول',
    termNumber: 1,
    startDate: '2026-02-01',
    currentWeek: 3,
    currentTopic: 'هفته ۳ - آردوینو و سنسورها',
    subscriptionPlan: 'economy',
    phase: 'فاز ۱ - مبانی IoT',
    progress: 28,
    lastContact: '2026-07-15',
    classesCompleted: 5,
    totalClasses: 18,
    reportCardDone: false,
  },
  {
    id: '6',
    name: 'سارا نجفی',
    username: 'sara.najafi',
    role: 'فراگیر',
    status: 'active',
    withdrawalWarning: false,
    course: 'Python پیشرفته',
    term: 'ترم چهارم',
    termNumber: 4,
    startDate: '2025-07-01',
    currentWeek: 14,
    currentTopic: 'هفته ۱۴ - پروژه نهایی',
    subscriptionPlan: 'premium',
    phase: 'فاز ۵ - پروژه نهایی',
    progress: 95,
    lastContact: '2026-08-05',
    classesCompleted: 28,
    totalClasses: 30,
    reportCardDone: true,
  },
  {
    id: '7',
    name: 'حسین موسوی',
    username: 'hossein.mousavi',
    role: 'فراگیر',
    status: 'withdrawn',
    withdrawalWarning: false,
    course: 'Scratch مقدماتی',
    term: 'ترم اول',
    termNumber: 1,
    startDate: '2025-12-01',
    currentWeek: 2,
    currentTopic: 'هفته ۲ - مبانی اسکرچ',
    subscriptionPlan: 'economy',
    phase: 'فاز ۱ - آشنایی با اسکرچ',
    progress: 15,
    lastContact: '2026-03-10',
    classesCompleted: 3,
    totalClasses: 18,
    reportCardDone: false,
  },
  {
    id: '8',
    name: 'مریم قاسمی',
    username: 'maryam.ghasemi',
    role: 'فراگیر',
    status: 'active',
    withdrawalWarning: true,
    course: 'App Inventor',
    term: 'ترم اول',
    termNumber: 1,
    startDate: '2026-03-01',
    currentWeek: 5,
    currentTopic: 'هفته ۵ - طراحی رابط کاربری',
    subscriptionPlan: 'vip',
    phase: 'فاز ۲ - ساخت اپ اولیه',
    progress: 45,
    lastContact: '2026-06-25',
    classesCompleted: 9,
    totalClasses: 20,
    reportCardDone: true,
  },
  {
    id: '9',
    name: 'رضا علوی',
    username: 'reza.alavi',
    role: 'فراگیر',
    status: 'active',
    withdrawalWarning: false,
    course: 'هوش مصنوعی مقدماتی',
    term: 'ترم سوم',
    termNumber: 3,
    startDate: '2025-09-15',
    currentWeek: 9,
    currentTopic: 'هفته ۹ - شبکه‌های عصبی',
    subscriptionPlan: 'premium',
    phase: 'فاز ۳ - مدل‌های پیشرفته',
    progress: 80,
    lastContact: '2026-07-30',
    classesCompleted: 18,
    totalClasses: 22,
    reportCardDone: true,
  },
  {
    id: '10',
    name: 'نیلوفر صادقی',
    username: 'nilufar.sadeghi',
    role: 'فراگیر',
    status: 'suspended',
    withdrawalWarning: false,
    course: 'IoT',
    term: 'ترم دوم',
    termNumber: 2,
    startDate: '2025-11-15',
    currentWeek: 7,
    currentTopic: 'هفته ۷ - ارتباطات بی‌سیم',
    subscriptionPlan: 'economy',
    phase: 'فاز ۲ - پروژه IoT',
    progress: 60,
    lastContact: '2026-04-18',
    classesCompleted: 13,
    totalClasses: 20,
    reportCardDone: false,
    suspensionReason: 'غیبت مکرر',
  },
  {
    id: '11',
    name: 'آرش جعفری',
    username: 'arash.jafari',
    role: 'فراگیر',
    status: 'active',
    withdrawalWarning: false,
    course: 'Python پیشرفته',
    term: 'ترم دوم',
    termNumber: 2,
    startDate: '2025-11-01',
    currentWeek: 7,
    currentTopic: 'هفته ۷ - کتابخانه NumPy',
    subscriptionPlan: 'vip',
    phase: 'فاز ۳ - داده‌کاوی',
    progress: 65,
    lastContact: '2026-08-03',
    classesCompleted: 14,
    totalClasses: 22,
    reportCardDone: true,
  },
  {
    id: '12',
    name: 'شیوا تهرانی',
    username: 'shiva.tehrani',
    role: 'فراگیر',
    status: 'withdrawn',
    withdrawalWarning: false,
    course: 'هوش مصنوعی مقدماتی',
    term: 'ترم اول',
    termNumber: 1,
    startDate: '2026-01-01',
    currentWeek: 1,
    currentTopic: 'هفته ۱ - مقدمه هوش مصنوعی',
    subscriptionPlan: 'economy',
    phase: 'فاز ۱ - مفاهیم پایه',
    progress: 8,
    lastContact: '2026-02-15',
    classesCompleted: 2,
    totalClasses: 18,
    reportCardDone: false,
  },
  {
    id: '13',
    name: 'کیان برزگر',
    username: 'kian.barzegar',
    role: 'فراگیر',
    status: 'active',
    withdrawalWarning: false,
    course: 'Scratch مقدماتی',
    term: 'ترم دوم',
    termNumber: 2,
    startDate: '2025-12-15',
    currentWeek: 6,
    currentTopic: 'هفته ۶ - انیمیشن و حرکت',
    subscriptionPlan: 'premium',
    phase: 'فاز ۲ - بازی‌سازی',
    progress: 55,
    lastContact: '2026-08-01',
    classesCompleted: 11,
    totalClasses: 20,
    reportCardDone: false,
  },
  {
    id: '14',
    name: 'پارمیس ایمانی',
    username: 'parmis.imani',
    role: 'فراگیر',
    status: 'active',
    withdrawalWarning: true,
    course: 'App Inventor',
    term: 'ترم سوم',
    termNumber: 3,
    startDate: '2025-08-01',
    currentWeek: 11,
    currentTopic: 'هفته ۱۱ - اتصال به API',
    subscriptionPlan: 'economy',
    phase: 'فاز ۴ - اپ پیشرفته',
    progress: 82,
    lastContact: '2026-06-30',
    classesCompleted: 22,
    totalClasses: 26,
    reportCardDone: true,
  },
  {
    id: '15',
    name: 'بهراد خسروی',
    username: 'behrad.khosravi',
    role: 'فراگیر',
    status: 'active',
    withdrawalWarning: false,
    course: 'IoT',
    term: 'ترم سوم',
    termNumber: 3,
    startDate: '2025-09-01',
    currentWeek: 10,
    currentTopic: 'هفته ۱۰ - پروژه هوشمندسازی خانه',
    subscriptionPlan: 'vip',
    phase: 'فاز ۳ - پروژه نهایی',
    progress: 90,
    lastContact: '2026-08-10',
    classesCompleted: 19,
    totalClasses: 22,
    reportCardDone: true,
  },
];

export const mockCallLogs: CallLog[] = [
  { id: 'c1', studentId: '1', studentName: 'علی رضایی', date: '2026-07-20', duration: 12, notes: 'پیشرفت خوب، سوالاتی درباره OOP داشت', result: 'answered' },
  { id: 'c2', studentId: '2', studentName: 'فاطمه محمدی', date: '2026-06-10', duration: 8, notes: 'نگران عقب‌ماندن از کلاس‌ها بود', result: 'answered' },
  { id: 'c3', studentId: '3', studentName: 'امیر حسینی', date: '2026-08-01', duration: 15, notes: 'راهنمایی پروژه نهایی', result: 'answered' },
  { id: 'c4', studentId: '4', studentName: 'زهرا کریمی', date: '2026-05-20', duration: 6, notes: 'پیگیری تعلیق حساب', result: 'answered' },
  { id: 'c5', studentId: '5', studentName: 'محمد احمدی', date: '2026-07-15', duration: 10, notes: 'توضیح مفاهیم آردوینو', result: 'answered' },
  { id: 'c6', studentId: '6', studentName: 'سارا نجفی', date: '2026-08-05', duration: 20, notes: 'بررسی پروژه نهایی - عالی بود', result: 'answered' },
  { id: 'c7', studentId: '7', studentName: 'حسین موسوی', date: '2026-03-10', duration: 5, notes: 'اعلام انصراف', result: 'answered' },
  { id: 'c8', studentId: '8', studentName: 'مریم قاسمی', date: '2026-06-25', duration: 0, notes: 'جواب نداد', result: 'no_answer' },
  { id: 'c9', studentId: '9', studentName: 'رضا علوی', date: '2026-07-30', duration: 18, notes: 'سوالات شبکه عصبی', result: 'answered' },
  { id: 'c10', studentId: '10', studentName: 'نیلوفر صادقی', date: '2026-04-18', duration: 0, notes: 'خط اشغال', result: 'busy' },
  { id: 'c11', studentId: '11', studentName: 'آرش جعفری', date: '2026-08-03', duration: 14, notes: 'مرور مباحث NumPy', result: 'answered' },
  { id: 'c12', studentId: '12', studentName: 'شیوا تهرانی', date: '2026-02-15', duration: 7, notes: 'پیگیری انصراف', result: 'answered' },
  { id: 'c13', studentId: '13', studentName: 'کیان برزگر', date: '2026-08-01', duration: 11, notes: 'راهنمایی پروژه بازی اسکرچ', result: 'answered' },
  { id: 'c14', studentId: '14', studentName: 'پارمیس ایمانی', date: '2026-06-30', duration: 9, notes: 'سوالاتی درباره API', result: 'answered' },
  { id: 'c15', studentId: '15', studentName: 'بهراد خسروی', date: '2026-08-10', duration: 22, notes: 'نمایش پروژه هوشمندسازی خانه', result: 'answered' },
  { id: 'c16', studentId: '1', studentName: 'علی رضایی', date: '2026-06-15', duration: 0, notes: 'جواب نداد', result: 'no_answer' },
  { id: 'c17', studentId: '2', studentName: 'فاطمه محمدی', date: '2026-05-01', duration: 5, notes: 'پیگیری غیبت', result: 'answered' },
  { id: 'c18', studentId: '8', studentName: 'مریم قاسمی', date: '2026-05-20', duration: 0, notes: 'جواب نداد', result: 'no_answer' },
  { id: 'c19', studentId: '13', studentName: 'کیان برزگر', date: '2026-07-10', duration: 0, notes: 'خط اشغال', result: 'busy' },
  { id: 'c20', studentId: '14', studentName: 'پارمیس ایمانی', date: '2026-07-25', duration: 0, notes: 'جواب نداد', result: 'no_answer' },
];

export const mockAttendance: AttendanceRecord[] = [
  { id: 'a1', studentId: '1', studentName: 'علی رضایی', sessionDate: '2026-08-05', sessionType: 'کلاس اصلی', present: true, duration: 90 },
  { id: 'a2', studentId: '2', studentName: 'فاطمه محمدی', sessionDate: '2026-08-05', sessionType: 'کلاس اصلی', present: false },
  { id: 'a3', studentId: '3', studentName: 'امیر حسینی', sessionDate: '2026-08-06', sessionType: 'جلسه گپینو', present: true, duration: 45 },
  { id: 'a4', studentId: '5', studentName: 'محمد احمدی', sessionDate: '2026-08-04', sessionType: 'کلاس اصلی', present: true, duration: 85 },
  { id: 'a5', studentId: '6', studentName: 'سارا نجفی', sessionDate: '2026-08-07', sessionType: 'کلاس اصلی', present: true, duration: 92 },
  { id: 'a6', studentId: '8', studentName: 'مریم قاسمی', sessionDate: '2026-08-05', sessionType: 'جلسه گپینو', present: true, duration: 50 },
  { id: 'a7', studentId: '9', studentName: 'رضا علوی', sessionDate: '2026-08-06', sessionType: 'کلاس اصلی', present: true, duration: 88 },
  { id: 'a8', studentId: '11', studentName: 'آرش جعفری', sessionDate: '2026-08-07', sessionType: 'کلاس اصلی', present: true, duration: 90 },
  { id: 'a9', studentId: '13', studentName: 'کیان برزگر', sessionDate: '2026-08-04', sessionType: 'کلاس اصلی', present: false },
  { id: 'a10', studentId: '14', studentName: 'پارمیس ایمانی', sessionDate: '2026-08-06', sessionType: 'کلاس اصلی', present: true, duration: 78 },
  { id: 'a11', studentId: '15', studentName: 'بهراد خسروی', sessionDate: '2026-08-07', sessionType: 'جلسه گپینو', present: true, duration: 60 },
  { id: 'a12', studentId: '1', studentName: 'علی رضایی', sessionDate: '2026-07-29', sessionType: 'کلاس اصلی', present: true, duration: 90 },
  { id: 'a13', studentId: '6', studentName: 'سارا نجفی', sessionDate: '2026-07-31', sessionType: 'جلسه گپینو', present: true, duration: 45 },
  { id: 'a14', studentId: '9', studentName: 'رضا علوی', sessionDate: '2026-07-30', sessionType: 'کلاس اصلی', present: true, duration: 85 },
  { id: 'a15', studentId: '3', studentName: 'امیر حسینی', sessionDate: '2026-07-28', sessionType: 'کلاس اصلی', present: true, duration: 90 },
];

export const instructorInfo = {
  name: 'مهدی پرحیدری',
  username: 'mahdi.porheydari',
  avatar: null,
  totalStudents: 15,
  activeStudents: 11,
};
